services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: container-ifsp-php
    restart: always
    volumes:
      - ./app:/var/www/html/
    networks:
      - prova-network
    ports:
      - "80:80"
    links:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: container-ifsp-mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha_da_nasa
      MYSQL_DATABASE: aval_acao
    networks:
      - prova-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: container-ifsp-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: mysql
    networks:
      - prova-network

networks:
  prova-network:
    driver: bridge

volumes:
  mysql:
